name: leetcode-automatic

services:
  lc-auto:
    image: ghcr.io/xieluyao60-coder/lc-auto:latest
    env_file:
      - .env
    volumes:
      - ./docker-data:/data
    working_dir: /data
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
